name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.aishasalmi }}
          password: ${{ secrets.Ddckr_pat_ACs9M_JiheIoM_rjbssRxlA-5wo }}

      - name: Build image (no push yet)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-quiz-ai:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-quiz-ai:${{ github.sha }}

      - name: Smoke test
        run: |
          docker run -d -p 5000:5000 --name quiz-test \
            -e GEMINI_KEY=dummy_key \
            -e STUDENT_ID=test123 \
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-quiz-ai:latest
          sleep 5
          curl --fail http://localhost:5000/api/health | grep ok
          docker stop quiz-test
          docker rm quiz-test

      - name: Push to Docker Hub
        if: github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-quiz-ai:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-quiz-ai:${{ github.sha }}

  deploy:
    needs: build-test-push
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_URL }}